server:
  port: 5297
spring:
  datasource:
    url:      jdbc:mysql://localhost:3306/student_management_system
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 10000
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
#    port: 465
    protocol: smtp
    username: 798327052@qq.com
    password: qkczxhejeofgbejc
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: true
    test-connection: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


